# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgmcp < Formula
  desc "PostgreSQL Model Context Protocol Server"
  homepage "https://github.com/subnetmarco/pgmcp"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_darwin_amd64.tar.gz"
      sha256 "0a4f2c11bf4539f247f6786d1ed1cdd430ff7a27ba1e45456b7b5128cbc091ef"

      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_darwin_arm64.tar.gz"
      sha256 "1e6cb3e2a9cdafba8a86868e922892d77390727f3b7f7e66e69efb15c83bad2c"

      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_linux_amd64.tar.gz"
      sha256 "42f4c22a206af283a9c2af0087144cbe56edb4d920e4e778a4e32d391ede77db"
      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_linux_arm64.tar.gz"
      sha256 "c765276c62e05b386d6dd76f28822417b39c70b2c25ccab8b8328100d31d95ce"
      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
  end

  test do
    system "#{bin}/pgmcp-server", "--version"
  end
end
