# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgmcp < Formula
  desc "PostgreSQL Model Context Protocol Server"
  homepage "https://github.com/subnetmarco/pgmcp"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_darwin_amd64.tar.gz"
      sha256 "7497b58cc8c3fbf579082002dd606baf4b7999b8646a9016e35778a91917da9e"

      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_darwin_arm64.tar.gz"
      sha256 "7da9a52c6347976e5260519e4c16a43f03ff151a4dd1b362a2ed72c2238093a7"

      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_linux_amd64.tar.gz"
      sha256 "4ceb47f3c7e9e926fd77004d9c48498c1a2362b0b7e80fe381d9dddf968a225a"
      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subnetmarco/pgmcp/releases/download/v0.3.0/pgmcp_0.3.0_linux_arm64.tar.gz"
      sha256 "cf3f4b281e698492bcb7f91cdadbaedaf454faf8c52648b92163b0b4471b9cf7"
      def install
        bin.install "pgmcp-server"
        bin.install "pgmcp-client"
      end
    end
  end

  test do
    system "#{bin}/pgmcp-server", "--version"
  end
end
